### ISSUE TITLE
kayak prod - image missing

### ISSUE THREAD

**Issue by KashunEnspirer** [Enspirer/kayak#11]
![7](https://user-images.githubusercontent.com/85350148/146189077-4009b348-8fbe-4617-8f29-7e7bcee76cc5.jpg)

**Comment by prasadbanuka** [comment]
![image](https://user-images.githubusercontent.com/84589746/146305490-14d6732f-6dbc-49c5-9b24-df94f6ffb60d.png)


It is still appear in there
