### ISSUE TITLE
icon - circular

### ISSUE THREAD

**Issue by KashunEnspirer** [Enspirer/kayak#5]
![1](https://user-images.githubusercontent.com/85350148/146186966-f4143a11-7b85-4c12-8f90-60ab626f9acd.jpg)

**Comment by prasadbanuka** [comment]
![icon fix](https://user-images.githubusercontent.com/84589746/146303748-8b5d2b68-ad04-421c-8c40-74496ad60267.png)

**Comment by prasadbanuka** [comment]
fixed
